create table if not exists public.wishes (
  id bigint generated by default as identity primary key,
  full_name text not null check (char_length(full_name) between 1 and 120),
  wish text not null check (char_length(wish) between 1 and 1000),
  image_url text not null,
  created_at timestamptz not null default now()
);

alter table public.wishes enable row level security;

drop policy if exists "wishes_insert" on public.wishes;
create policy "wishes_insert"
on public.wishes
for insert
to anon
with check (
  char_length(full_name) between 1 and 120
  and char_length(wish) between 1 and 5000
  and image_url like 'https://sacorzxlnhuiwnxswcwz.supabase.co/storage/v1/object/public/selfie_images/%'
);

drop policy if exists "wishes_query" on public.wishes;
create policy "wishes_query"
on public.wishes
for select
to anon
using (true);

grant insert on table public.wishes to anon;
grant select (full_name, wish, image_url, created_at) on table public.wishes to anon;
grant usage, select on sequence public.wishes_id_seq to anon;
